### ISSUE TITLE
Account data returned from 3.1 `/accounts` endpoint contains incorrect scheme name value

### ISSUE THREAD

**Issue by BohoCode** [OpenBankingToolkit/openbanking-aspsp#215]
Customer Issue: 48067

The response from the `/open-banking/v3.1/aisp/accounts` endpoint returns the following sample data;

```
"Data": {
           "Account": [
             {
               "AccountId": "0cdaa0d0-0875-492d-be47-df617a1d42fe",
               "Currency": "GBP",
               "AccountType": "Personal",
               "AccountSubType": "CreditCard",
               "Account": [
                 {
                   "SchemeName": "PAN",
                   "Identification": "525302******7553",
                   "Name": "Mr Zak Matusak"
                 }
               ]
             },
             {
               "AccountId": "1957ee43-faae-4601-bb73-140259039e38",
               "Currency": "GBP",
               "AccountType": "Personal",
               "AccountSubType": "CurrentAccount",
               "Nickname": "NickZero",
               "Account": [
                 {
                   "SchemeName": "SortCodeAccountNumber",
                   "Identification": "80064711123468",
                   "Name": "Mr Zak Matusak"
                 }
               ]
             } ...
```

As you will notice, "SchemeName” is appearing as **SortCodeAccountNumber**. This should appear as **UK.OBIE.SortCodeAccountNumber**.

**Comment by BohoCode** [comment]
Jorge's update in the customer issue;
docs: https://openbanking.atlassian.net/wiki/spaces/DZ/pages/937623627/Accounts+v3.1

Source to check:
- openbanking-uk-datamodel:
OBExternalAccountIdentification3Code Correct object for v3.0 and lower
OBExternalAccountIdentification4Code Correct object for v.3.1
- openabnking-aspsp:
forgerock-openbanking-uk-aspsp-rs-gateway/...gateway-server
@Controller("AccountsApiV2.0")
public class AccountsApiController implements AccountsApi {
Api 3.1 extends v3.0 and v3.0 extends v2.0

**Comment by matt-wills** [comment]
PRs merge and change tested.
